# Generated by Django 6.1.1 on 2026-09-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvester_repository_id', models.CharField(db_index=True, max_length=64, verbose_name='identificador no Harvester')),
                ('acronym', models.CharField(max_length=32, verbose_name='sigla')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='associado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_accesses', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'acesso a repositório',
                'verbose_name_plural': 'acessos a repositórios',
                'ordering': ['acronym'],
                'constraints': [models.UniqueConstraint(fields=('user', 'harvester_repository_id'), name='unique_user_repository')],
            },
        ),
    ]
