# Generated by Django 6.1.1 on 2026-09-18 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('category', models.CharField(choices=[('COMUNICACAO', 'Comunicação'), ('NOVIDADES', 'Novidades'), ('COLETA', 'Coleta'), ('VALIDACAO', 'Validação')], max_length=16, verbose_name='categoria')),
                ('harvester_repository_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='identificador no Harvester')),
                ('acronym', models.CharField(blank=True, max_length=32, verbose_name='sigla')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criada em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lida em')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='lida por')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatário')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(condition=models.Q(('read_at__isnull', True)), fields=['harvester_repository_id'], name='notif_repo_nao_lida'), models.Index(fields=['recipient', '-created_at'], name='notif_dest_criada')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recipient__isnull', True), models.Q(('harvester_repository_id', ''), _negated=True)), models.Q(('recipient__isnull', False), ('harvester_repository_id', '')), _connector='OR'), name='notification_destino_unico'), models.CheckConstraint(condition=models.Q(('read_at__isnull', False), ('read_by__isnull', True), _connector='OR'), name='notification_leitura_coerente')],
            },
        ),
    ]
