# Generated by Django 6.1.1 on 2026-09-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='requires_acknowledgement',
            field=models.BooleanField(default=False, verbose_name='exige visto'),
        ),
    ]
