# Generated by Django 6.1.1 on 2026-09-19 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_requires_acknowledgement'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='código')),
                ('name_pt_br', models.CharField(max_length=48, verbose_name='nome (pt-BR)')),
                ('name_es', models.CharField(blank=True, max_length=48, verbose_name='nome (es)')),
                ('name_en', models.CharField(blank=True, max_length=48, verbose_name='nome (en)')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
            ],
            options={
                'verbose_name': 'categoria de notificação',
                'verbose_name_plural': 'categorias de notificação',
                'ordering': ['name_pt_br'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.notificationcategory', verbose_name='categoria'),
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, verbose_name='nome do modelo')),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationcategory', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'texto padrão',
                'verbose_name_plural': 'textos padrão',
                'ordering': ['category__name_pt_br', 'label'],
                'constraints': [models.UniqueConstraint(fields=('category', 'label'), name='unique_template_por_categoria')],
            },
        ),
    ]
