# Generated by Django 6.1.1 on 2026-09-21 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_categoria_vira_chave'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True, verbose_name='dispensada em')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissals', to='notifications.notification', verbose_name='notificação')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_dismissals', to=settings.AUTH_USER_MODEL, verbose_name='dispensada por')),
            ],
            options={
                'verbose_name': 'dispensa de notificação',
                'verbose_name_plural': 'dispensas de notificação',
                'ordering': ['-dismissed_at'],
                'indexes': [models.Index(fields=['user'], name='dispensa_por_usuario')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'user'), name='dispensa_unica_por_pessoa')],
            },
        ),
    ]
