# Generated by Django 6.1.1 on 2026-09-14 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Autenticação'), ('LOGOUT', 'Encerramento de sessão'), ('CREATE', 'Criação'), ('UPDATE', 'Alteração'), ('DELETE', 'Exclusão'), ('EXPORT', 'Exportação'), ('HARVEST', 'Coleta')], max_length=16, verbose_name='ação')),
                ('resource', models.CharField(max_length=64, verbose_name='recurso')),
                ('resource_id', models.CharField(blank=True, max_length=64, verbose_name='identificador do recurso')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['resource', 'resource_id'], name='audit_audit_resourc_3e0c90_idx')],
            },
        ),
    ]
