# Generated by Django 6.1.1 on 2026-09-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution',
            field=models.CharField(blank=True, help_text='Instituição à qual o gestor está vinculado.', max_length=200, verbose_name='instituição'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefone de contato, com DDD.', max_length=32, verbose_name='telefone para contato'),
        ),
    ]
