# Generated by Django 6.1.1 on 2026-09-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_institution_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department_email',
            field=models.EmailField(blank=True, help_text='E-mail institucional do departamento ou setor, para contato da equipe.', max_length=254, verbose_name='e-mail do departamento/setor'),
        ),
    ]
