# Generated by Django 6.1.1 on 2026-09-19 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvester_repository_id', models.CharField(db_index=True, max_length=64, verbose_name='identificador no Harvester')),
                ('acronym', models.CharField(blank=True, max_length=32, verbose_name='sigla')),
                ('note', models.TextField(blank=True, verbose_name='justificativa')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ATENDIDA', 'Atendida'), ('RECUSADA', 'Recusada')], db_index=True, default='PENDENTE', max_length=16, verbose_name='situação')),
                ('snapshot_id', models.CharField(blank=True, max_length=64, verbose_name='coleta realizada')),
                ('reason', models.TextField(blank=True, verbose_name='motivo da recusa')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolvida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='aberta em')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_requests', to=settings.AUTH_USER_MODEL, verbose_name='solicitante')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_requests_resolved', to=settings.AUTH_USER_MODEL, verbose_name='resolvida por')),
            ],
            options={
                'verbose_name': 'demanda de coleta',
                'verbose_name_plural': 'demandas de coleta',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='demands_har_status_0aa4b7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('harvester_repository_id',), name='uma_demanda_pendente_por_repositorio'), models.CheckConstraint(condition=models.Q(models.Q(('reason', ''), ('resolved_at__isnull', True), ('snapshot_id', ''), ('status', 'PENDENTE')), models.Q(('reason', ''), ('resolved_at__isnull', False), ('status', 'ATENDIDA'), models.Q(('snapshot_id', ''), _negated=True)), models.Q(('resolved_at__isnull', False), ('snapshot_id', ''), ('status', 'RECUSADA'), models.Q(('reason', ''), _negated=True)), _connector='OR'), name='demanda_coerente_com_a_situacao')],
            },
        ),
    ]
